### ISSUE TITLE
Windows builds broken?

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/segalign-feedstock#3]
It looks like this package builds for Windows. However the Windows builds are all failing (please [see these builds]( https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=874176&view=results ))

Given this, should Windows be skipped?

Or is Windows suppose to work?

**Comment by richard-burhans** [comment]
Yes, for now the Windows builds should be skipped.   A fix (and a change to the requirements) can be found here:  https://github.com/conda-forge/segalign-feedstock/pull/4
